### PR TITLE
Covert to using pytest for the test runner

### PR DESCRIPTION
**Pull request by sudorandom**

### CODE REVIEW

**Comment by briancline** [comment]
What are the advantages?

**Comment by sudorandom** [comment]
@briancline  Mostly, better output when assertions fail.

**Comment by sudorandom** [comment]
I also moved the tests out from under the SoftLayer module... If you hit any issues updating to this, run this to clear out __pycache__ and pyc files:

```bash
find . | grep -E "(__pycache__|\.pyc$)" | xargs rm -rf
```

**Comment by sudorandom** [comment]
@underscorephil This is g2g. The coverage drop is expected... The coverage that it shows now is more accurate.

**Pull request merged**
