### PR TITLE
Update file & block volume-detail commands to show duplicate volume info

### PR DESCRIPTION
**Pull request by dpickle2**
[This pull request is being opened now for review, but it should not be merged in yet as some work is still pending on the backend for duplication features to be fully supported.]

### CODE REVIEW

**Comment by iodine53** [comment]
It seems like it'd be a good idea to merge this into #830 maybe?

**Comment by dpickle2** [comment]
I'm happy to merge this into #829 if desired. Should I go ahead and do that?

**Comment by iodine53** [comment]
I'm thinking so; while they aren't strictly dependent on each other, one shouldn't be released without the other, so combining them would make sense.

**Comment by dpickle2** [comment]
I have merged the commit into the feature/volume-duplicate branch, so these changes are now included in #830 .

**Pull request closed without merging**
