### PR TITLE
block/file volume-options improvements 2

### PR DESCRIPTION
**Pull request by caberos**
[#issue1693](https://github.com/softlayer/softlayer-python/issues/1693)

https://github.com/softlayer/softlayer-python/issues/1693

### CODE REVIEW

**Review by BrianSantivanez — APPROVED** [review]
image
image
Looks good to me

**Review by allmightyspiff — CHANGES_REQUESTED** [review]
Looks good, just fix the merge conflicts. Thanks

**Comment by edsonarios** [comment]
Screenshots of the test result
image
image

**Review by edsonarios — APPROVED** [review]
Looks good to me

**Review by allmightyspiff — APPROVED** [review]

**Pull request merged**
