### PR TITLE
Bandwidth pool management

### PR DESCRIPTION
**Pull request by caberos**
https://github.com/softlayer/softlayer-python/issues/1577

### CODE REVIEW

**Comment by BrianSantivanez** [comment]
Running the help command
image

Running the command with an id that does not exist
image

Id´s used to test
image

Running the command with first id
image

Running the command with a second id
image

**Comment by edsonarios** [comment]
Test new feature
image
image
image

Maybe it's necessary to see the id of the results, because when I want to see the detail of a region, I need the id
image

**Comment by allmightyspiff** [comment]
> For found the id of the any region, maybe we need the id of the follow command "slcli account bandwidth-pools" but in this commando not show us the id
I created #1585  to address this.

**Comment by BrianSantivanez** [comment]
image

When command is run with 1092822 and 138442 is falling

image

image

**Review by edsonarios — APPROVED** [review]
Looks good to me

**Review by allmightyspiff — APPROVED** [review]

**Pull request merged**
