### PR TITLE
add new feature on vlan

### PR DESCRIPTION
**Pull request by caberos**
https://github.com/softlayer/softlayer-python/issues/1571

### CODE REVIEW

**Comment by allmightyspiff** [comment]
@BrianSantivanez / @edsonarios when you get a chance can you test this change to make sure it works as expected. Post some screenshots of the output, and any issues you may find when testing to this issue. Thanks

**Review by allmightyspiff — CHANGES_REQUESTED** [review]
Code looks good, just capitalize the first letter of column headers. Also need some unit test coverage for the manager functions you added.

**Comment by BrianSantivanez** [comment]
> @BrianSantivanez / @edsonarios when you get a chance can you test this change to make sure it works as expected. Post some screenshots of the output, and any issues you may find when testing to this issue. Thanks

When I run the test, it is passing
image
The new feature is returning the datacenter and router options to create a vlan in table format and json format, it looks good to me.
image
image

**Comment by edsonarios** [comment]
> @BrianSantivanez / @edsonarios when you get a chance can you test this change to make sure it works as expected. Post some screenshots of the output, and any issues you may find when testing to this issue. Thanks

I test this new feature and I attache some screenshots
In performance, it takes about 50 seconds to deliver the result
image
image

But I think a help functionality is missing, for example in ibmcloud we have a description
image
image

**Review by allmightyspiff — APPROVED** [review]
Looks good, thanks

**Comment by allmightyspiff** [comment]
@edsonarios I think the options in the `ibmcloud` command are actually a bit out of date. Currently you really only need the router/datacenter when ordering a VLAN.

image

Might need to update the `ibmcloud` command to reflect that though.

**Pull request merged**
