### PR TITLE
Updated command - slcli account bandwidth-pools

### PR DESCRIPTION
**Pull request by edsonarios**
Issue: #1937 
```
softlayer-python/ (issue1933) $ slcli account bandwidth-pools
                                                  Bandwidth Pools
┌─────────┬──────────────────────┬─────────────────┬─────────┬────────────┬───────────────┬─────────────────┬──────┐
│ Id      │ Name                 │ Region          │ Devices │ Allocation │ Current Usage │ Projected Usage │ Cost │
├─────────┼──────────────────────┼─────────────────┼─────────┼────────────┼───────────────┼─────────────────┼──────┤
```

### CODE REVIEW

**Review by caberos — APPROVED** [review]
LGTM

**Comment by ramkishor-ch** [comment]
Hi @edsonarios,

When I tried to test the code changes, I am getting an error.

Example:
./slcli account bandwidth-pools Bandwidth Pools
Usage: slcli account bandwidth-pools [OPTIONS]

Try 'slcli account bandwidth-pools --help' for help.

**Error:** Got unexpected extra arguments (Bandwidth Pools)

Can you please fix it.

Thanks,
Ramkishor Chaladi.

**Comment by edsonarios** [comment]
Hi @ramkishor-ch can you upload a screenshot with the error please, I tested and works without problem.
image
image

Thanks.

**Comment by ramkishor-ch** [comment]
Hi @edsonarios,

Actually I have miss typed it, Now It is working fine.

I have tested the code changes.

Please find the screenshots.

Screen Shot: 1
Screenshot 2023-05-19 at 6 48 48 PM


Screen Shot: 2
Screenshot 2023-05-19 at 6 45 15 PM

Thanks,
Ramkishor Chaladi.

**Review by allmightyspiff — APPROVED** [review]

**Pull request merged**
