### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by corneil**
The zone id was referred to as zone name in a few places.

### CODE REVIEW

**Comment by sudorandom** [comment]
@underscorephil @allmightyspiff Has @corneil signed the CLA? (https://github.com/softlayer/softlayer-python/blob/master/CONTRIBUTING.md).

**Comment by underscorephil** [comment]
@sudorandom i dont have one

**Comment by sudorandom** [comment]
@corneil If you haven't already, could you please follow the instructions on this page? https://github.com/softlayer/softlayer-python/blob/master/docs/cla-individual.md

Your change is, indeed, useful so I want to be okay with pulling it in. :v:

**Comment by sudorandom** [comment]
@corneil: Ping. I'd like to merge this in but I can't until we get a CLA for you.

**Pull request closed without merging**
