### PR TITLE
Add the option to add and upgrade the hw disk.

### PR DESCRIPTION
**Pull request by FernandoOjeda**
Add the option to add and upgrade the hw disk.
#1444

### CODE REVIEW

**Review by allmightyspiff — APPROVED** [review]
Looks good. @atge / @caberos  would you mind testing this and putting some results in the issue.

Thanks.

**Review by caberos — APPROVED** [review]
LGTM

**Review by ATGE — COMMENTED** [review]
### Testing 
- ❌`$ slcli hw upgrade 1867001 --test --resize-disk 1000 1 --resize-disk 2000 2`
`SoftLayerAPIError(404): Function ("createObject") is not a valid method for this service.`
- ❌ `$ slcli hw upgrade 1867001 --test --resize-disk 1000 1`
`SoftLayerAPIError(404): Function ("createObject") is not a valid method for this service.`
 - ❌`$ slcli hw upgrade 1867001 --test --add-disk 1000 3 --add-disk 2000 4`
`SoftLayerAPIError(404): Function ("createObject") is not a valid method for this service.`
- ❌`$ slcli hw upgrade 1867001 --test --add-disk 1000 3`
`SoftLayerAPIError(404): Function ("createObject") is not a valid method for this service.`
```bash
$python3 --version
Python 3.6.7
$ lsb_release -a
Description:    Ubuntu 18.04.5 LTS
```

**Comment by FernandoOjeda** [comment]
image
image
image
image

**Review by allmightyspiff — CHANGES_REQUESTED** [review]
With the REST endpoint, I get the following error as well:

```
$ ./slcli -vvv hw upgrade 1867001 --test --resize-disk 1000 1 --resize-disk 2000 2
Calling: SoftLayer_Hardware_Server::getUpgradeItemPrices(id=1867001, mask='mask[id,locationGroupId,categories[name,id,categoryCode],item[keyName,description,capacity,units]]', filter='None', args=(True,), limit=None, offset=None))
Starting new HTTPS connection (1): api.softlayer.com:443
https://api.softlayer.com:443 "POST /rest/v3.1/SoftLayer_Hardware_Server/1867001/getUpgradeItemPrices.json?objectMask=mask%5Bid%2ClocationGroupId%2Ccategories%5Bname%2Cid%2CcategoryCode%5D%2Citem%5BkeyName%2Cdescription%2Ccapacity%2Cunits%5D%5D HTTP/1.1" 404 115
Returned Data:
None
curl -u $SL_USER:$SL_APIKEY -X POST -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, compress" -d '{"parameters": [true]}' 'https://api.softlayer.com/rest/v3.1/SoftLayer_Hardware_Server/1867001/getUpgradeItemPrices.json?objectMask=mask%5Bid%2ClocationGroupId%2Ccategories%5Bname%2Cid%2CcategoryCode%5D%2Citem%5BkeyName%2Cdescription%2Ccapacity%2Cunits%5D%5D'
SoftLayerAPIError(404): Function ("createObject") is not a valid method for this service.
```

This seems to be because [def _get_upgrade_prices()](https://github.com/softlayer/softlayer-python/blob/24f7bb9e23c3d7d7153c9f4c1d71831a1c16a2a5/SoftLayer/managers/hardware.py#L899) makes this API call:

```
 return self.hardware.getUpgradeItemPrices(include_downgrade_options, id=instance_id, mask=mask)
```

but [SoftLayer_Hardware_Server::getUpgradeItemPrices](https://sldn.softlayer.com/reference/services/SoftLayer_Hardware_Server/getUpgradeItemPrices/) doesn't take in any arguments, so the REST endpoint is throwing this exception.

Changing that API call to not pass in include_downgrade_options should make this change work in both REST and XMLRPC

**Comment by allmightyspiff** [comment]
✔️ `./slcli -vvv hw upgrade 1867001 --test --resize-disk 1000 1 --resize-disk 2000 2`
✔️ `./slcli hw upgrade 1867001 --test --resize-disk 1000 1` 
✔️ `./slcli hw upgrade 1867001 --test --add-disk 1000 3 --add-disk 2000 4`
> The item price was not found for disk4 with 'capacity:' 2000

I'm assuming thats expected here.

✔️ `./slcli hw upgrade 1867001 --test --add-disk 1000 3`



TODO: Once this is merged, I'd like the output of this command to be a receipt type of table. And have a difference between the TEST and actual order placing.

**Review by allmightyspiff — APPROVED** [review]

**Pull request merged**
