### PR TITLE
`slcli account billing-items --create` always return an empty table

### PR DESCRIPTION
**Pull request by BrianSantivanez**
Issue: https://github.com/softlayer/softlayer-python/issues/1964
Observations: the filter was updated to can use the option --create
```
slcli account  billing-items --create 2022-10-26
                                                 Billing Items
┌────────────┬─────────────┬──────┬────────────────────────┬────────────┬─────────────────────────────┬───────┐
│     Id     │ Create Date │ Cost │ Category Code          │ Ordered By │ Description                 │ Notes │
├────────────┼─────────────┼──────┼────────────────────────┼────────────┼─────────────────────────────┼───────┤
│ 1004472488 │ 2022-10-26  │ 0.0  │ gateway_resource_group │  ChechuA   │ Gateway Appliance Cluster   │ None  │
│ 1004515848 │ 2022-10-26  │ 0.0  │ server                 │  ChechuA   │ fra02-ocp-virt.chechu.me    │ None  │
│ 1004515882 │ 2022-10-26  │ 0.0  │ gateway_resource_group │  ChechuA   │ Gateway Appliance Cluster   │ None  │
│ 1004602572 │ 2022-10-26  │ 0.0  │ guest_storage          │    IBM     │ Image Template Storage      │ None  │
│ 1004604862 │ 2022-10-26  │ 0.0  │ server                 │  ChechuA   │ ocp-virt-worker-2.chechu.me │ None  │
│ 1004605364 │ 2022-10-26  │ 0.0  │ guest_core             │  ChechuA   │ pxe-1.chechu.me             │ None  │
│ 1004612494 │ 2022-10-26  │ 0.0  │ server                 │  ChechuA   │ ocp-virt-worker-1.chechu.me │ None  │
└────────────┴─────────────┴──────┴────────────────────────┴────────────┴─────────────────────────────┴───────┘
slcli account  billing-items --create 2014-02-22
                                         Billing Items
┌──────────┬─────────────┬──────┬───────────────┬────────────┬────────────────────────┬───────┐
│    Id    │ Create Date │ Cost │ Category Code │ Ordered By │ Description            │ Notes │
├──────────┼─────────────┼──────┼───────────────┼────────────┼────────────────────────┼───────┤
│ 19388750 │ 2014-02-22  │ 0.0  │ guest_storage │    IBM     │ Image Template Storage │ None  │
└──────────┴─────────────┴──────┴───────────────┴────────────┴────────────────────────┴───────┘

```

### CODE REVIEW

**Comment by edsonarios** [comment]
Screenshots of the test result
image
image

**Review by edsonarios — APPROVED** [review]
Looks good to me

**Review by ramkishor-ch — APPROVED** [review]
Hi,
I have "tested the changes".
Approving the Pull Request.
Thanks,
Ramkishor Chaladi.

**Comment by JayasilanJibm** [comment]
Hi,

I have tested the changes. Looks fine to me.
Approving the Pull Request.

Thanks,
Jayasilan

**Review by JayasilanJibm — APPROVED** [review]

**Pull request merged**
