### PR TITLE
Group bandwidth commands

### PR DESCRIPTION
**Pull request by edsonarios**
Issue: #1961 
Additionally, continue the old commands as an alias
```
softlayer-python/ (issue1961) $ slcli bandwidth
Usage: slcli bandwidth [OPTIONS] COMMAND [ARGS] ...

        Bandwidth.

┌────┬────────┬─────────────────────────────┐
│ -h │ --help │ Show this message and exit. │
└────┴────────┴─────────────────────────────┘

Commands:
  pools         Displays bandwidth pool information
  pools-detail  Get bandwidth pool details.
  summary       Bandwidth report for every pool/server
```

### CODE REVIEW

**Comment by ramkishor-ch** [comment]
Hi,

I have "tested the changes".
Please find the screenshots for reference.

Screen Shot: 1
Screenshot 2023-05-30 at 1 12 29 PM


Screen Shot: 2
Screenshot 2023-05-30 at 1 12 53 PM


Thanks,
Ramkishor Chaladi.

**Review by ramkishor-ch — APPROVED** [review]
Hi,
I have "tested the changes".
Approving the Pull Request.
Thanks,
Ramkishor Chaladi.

**Comment by JayasilanJibm** [comment]
Hi,

I have tested the changes and verified as well.

Approving the pull request.

Sharing the screenshot for further reference.

Screenshot 2023-06-07 at 6 42 59 PM

Screenshot 2023-06-07 at 6 43 47 PM

Screenshot 2023-06-07 at 6 44 17 PM

Screenshot 2023-06-07 at 6 45 26 PM



Thanks,
Jayasilan

**Review by caberos — APPROVED** [review]
LGTM

**Pull request merged**
