### PR TITLE
add a new column on ipAddress table subnet details

### PR DESCRIPTION
**Pull request by caberos**
[#issue1952](https://github.com/softlayer/softlayer-python/issues/1952)

image

### CODE REVIEW

**Review by BrianSantivanez — APPROVED** [review]
Looks good to me 
image

**Comment by ramkishor-ch** [comment]
Hi,

I have "tested the changes".
Please find the screenshots for reference.

Screen Shot: 1
1_Screenshot 2023-05-23 at 1 28 54 PM


Screen Shot: 2
2_Screenshot 2023-05-23 at 1 29 35 PM


Thanks,
Ramkishor Chaladi.

**Review by edsonarios — APPROVED** [review]
Looks good to me

**Comment by JayasilanJibm** [comment]
Screenshot 2023-05-29 at 9 14 00 PM

Hi
I have tested the changes for subnet detail.
Please find the screenshot.

Thanks,
Jayasilan

**Review by JayasilanJibm — APPROVED** [review]

**Pull request merged**
