### PR TITLE
Refactor slcli hw detail prices.

### PR DESCRIPTION
**Pull request by FernandoOjeda**
Refactor slcli hw detail prices https://github.com/softlayer/softlayer-python/issues/1441.

### CODE REVIEW

**Comment by FernandoOjeda** [comment]
@allmightyspiff Would you like to add a categorycode information to the prices table.
image

**Review by caberos — APPROVED** [review]
LGTM.

**Review by ATGE — COMMENTED** [review]
looks good

**Review by allmightyspiff — APPROVED** [review]

**Comment by allmightyspiff** [comment]
I like the category code inclusion, looks good.

**Pull request merged**
