### PR TITLE
Add getting package by key for use in hardware manager

### PR DESCRIPTION
**Pull request by kwienken**
This addresses the issue I opened, #809.

### CODE REVIEW

**Comment by allmightyspiff** [comment]
Can you apply this change to  https://github.com/softlayer/softlayer-python/blob/c7e3d847c6b4533514a0860702a519d6a5004ea6/SoftLayer/managers/vs.py#L817  
so that both hardware and virtual use your get_package_by_key method, then we can remove 

get_package_id_by_type
get_package_by_type
get_packages_of_type
from the ordering manager and clean it up a bit.

**Comment by kwienken** [comment]
@allmightyspiff I've updated the virtual manager to use get_package_by_key but I left the _by_type methods in the ordering manager. After talking with @sergiocarlosmorales I think it's best that we leave them in to prevent breaking other users applications that may include the package and use the ordering library.

**Comment by sergiocarlosmorales** [comment]
Agree here, if we were to remove that functionality we might break existing customer implementations and since it would be backwards incompatible, we'd likely need to bump the release version. Too much, let's keep it simple for now :)

**Comment by camporter** [comment]
There appears to be reports of issues with packages having the same type and the package not being chosen here before this change (on 5.2.1). @allmightyspiff any way we could get a new minor or bugfix release out with this included?

**Comment by allmightyspiff** [comment]
5.2.3 is now released.

**Pull request merged**
