### PR TITLE
Security groups

### PR DESCRIPTION
**Pull request by rlrossiter**
This change adds security groups CLIs. It also adds helpers for manipulating security groups to the network manager. Security groups can be added to a VSI at order time, so public and private security groups were added to the ordering helper.

### CODE REVIEW

**Comment by allmightyspiff** [comment]
This looks good to me so far, although I'll want to test it locally myself before merging.
Is this ready to merge or are you still working on it?

**Comment by rlrossiter** [comment]
If you try it out, take a look, and find nothing wrong with it, it's ready to merge. I have no further changes I'm looking to make on it.

**Comment by allmightyspiff** [comment]
since this looks to still be in beta I think I will hold off on merging until its released officially for everyone. Otherwise the change looks good and works for me.


## Change Log
* Added sg / securitygroup command
```
Usage: slcli sg [OPTIONS] COMMAND [ARGS]...

  Network security groups.

Options:
  -h, --help  Show this message and exit.

Commands:
  create            Create a security group.
  delete            Deletes the given security group
  detail            Get details about a security group.
  edit              Edit details of a security group.
  interface-add     Attach an interface to a security group.
  interface-list    List interfaces associated with security...
  interface-remove  Detach an interface from a security group.
  list              List security groups.
  rule-add          Add a security group rule to a security...
  rule-edit         Edit a security group rule in a security...
  rule-list         List security group rules.
  rule-remove       Remove a rule from a security group.
```

**Comment by Neetuj** [comment]
@allmightyspiff we are not in open Beta .. which means we have publicized this offering. https://twitter.com/IBMBluemix/status/895048755896045569
bit.ly/2vBoAiF 

I think this will be a good time to merge this PR. 
@rlrossiter you all set for this to be merged?

**Comment by Neetuj** [comment]
PR LGTM

**Comment by allmightyspiff** [comment]
@Neetuj thanks for that confirmation. I'll merge and release this today.

**Comment by rlrossiter** [comment]
I added a type check to one of the manager functions for security groups. This is now ready to go. 👍

**Pull request merged**
