### PR TITLE
Add pricing date to slcli order preset-list

### PR DESCRIPTION
**Pull request by caberos**
https://github.com/softlayer/softlayer-python/issues/1574

### CODE REVIEW

**Comment by allmightyspiff** [comment]
@edsonarios would you mind testing this change, thanks.

**Review by allmightyspiff — APPROVED** [review]
Code looks good, thanks

**Comment by edsonarios** [comment]
Screenshots of the feature
image
image
image

image

image

image
image
image
image

**Comment by edsonarios** [comment]
Looks good to me

**Review by edsonarios — APPROVED** [review]
Looks good to me

**Pull request merged**
