### PR TITLE
block/volume-detail: add iops details for endurance storage

### PR DESCRIPTION
**Pull request by houstar**
Signed-off-by: Leno Hou <houqy@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by allmightyspiff** [comment]
Also, update the unit tests so they pass Travis CI. You can likely just change the test to not check for the mask as I don't think thats a very good test.

**Comment by houstar** [comment]
@allmightyspiff Could you help me to skip the mask check ?

**Comment by allmightyspiff** [comment]
The current test is 

tests/managers/block_tests.py
```
    def test_get_block_volume_details(self):
        result = self.block.get_block_volume_details(100)

        self.assertEqual(fixtures.SoftLayer_Network_Storage.getObject, result)

        expected_mask = 'id,'\
                        'username,'\
                        'password,'\
                        'capacityGb,'\
                        'snapshotCapacityGb,'\
                        'parentVolume.snapshotSizeBytes,'\
                        'storageType.keyName,'\
                        'serviceResource.datacenter[name],'\
                        'serviceResourceBackendIpAddress,'\
                        'storageTierLevel,'\
                        'iops,'\
                        'lunId,'\
                        'originalVolumeName,'\
                        'originalSnapshotName,'\
                        'originalVolumeSize,'\
                        'activeTransactionCount,'\
                        'activeTransactions.transactionStatus[friendlyName],'\
                        'replicationPartnerCount,'\
                        'replicationStatus,'\
                        'replicationPartners[id,username,'\
                        'serviceResourceBackendIpAddress,'\
                        'serviceResource[datacenter[name]],'\
                        'replicationSchedule[type[keyname]]]'

        self.assert_called_with(
            'SoftLayer_Network_Storage',
            'getObject',
            identifier=100,
            mask='mask[%s]' % expected_mask
            )
```

I'd either update the mask to match what you changed it to, or just remove the mask along with the "mask='mask[%s]' % expected_mask" bit on self.assert_called_with.

To test locally, you can use "tox" to run the test suite to make sure it all works.

**Comment by allmightyspiff** [comment]
I'm going to address this in #912

**Pull request closed without merging**
