### PR TITLE
Figure out why slcli vs list --tag <tagName> doesnt work properly

### PR DESCRIPTION
**Pull request by caberos**
[#issue1957](https://github.com/softlayer/softlayer-python/issues/1957)

image

### CODE REVIEW

**Comment by edsonarios** [comment]
Screenshots of the test result
image

**Review by edsonarios — APPROVED** [review]
Looks good to me

**Comment by ramkishor-ch** [comment]
Hi,

I have "tested the changes".
Please find the screenshot for reference.

Screen Shot: 1
Screenshot 2023-05-24 at 6 36 58 PM


Thanks,
Ramkishor Chaladi.

**Review by ramkishor-ch — APPROVED** [review]
Hi
I have "tested the changes".
Approving the Pull Request.
Thanks,
Ramkishor Chaladi.

**Review by allmightyspiff — APPROVED** [review]

**Pull request merged**
