### PR TITLE
Removing the rwhois commands

### LINKED ISSUE #1352: RWHOIS is deprecated, replace it or remove it.
Commands in question are part of `SoftLayer.CLI.rwhois`

https://sldn.softlayer.com/reference/services/SoftLayer_Account/getRwhoisData/
https://sldn.softlayer.com/reference/services/SoftLayer_Network_Subnet_Rwhois_Data/

Should use `SoftLayer_Account_Regional_Registry_Detail ` and `SoftLayer_Network_Subnet_Registration ` instead apparently.

Aside from the old commands being deprecated, at the moment i'm not sure what replacing them will involve, this is just to remind me to fix it eventually.

### PR DESCRIPTION
**Pull request by allmightyspiff**
Fixes #1352

### CODE REVIEW

**Review by FernandoOjeda — APPROVED** [review]
LGTM

**Review by caberos — APPROVED** [review]
LGTM.

**Review by ATGE — COMMENTED** [review]
### Testing

- ✔️ `$ slcli -h | grep rw`
   `$`

- ✔️ `$ slcli rwhois -h`
```
Usage: slcli [OPTIONS] COMMAND [ARGS]...
Try "slcli -h" for help.

Error: No such command "rwhois".
```
looks good, just there is a reference within [docs/cli.rst](https://github.com/allmightyspiff/softlayer-python/blob/rwhois_removal/docs/cli.rst#usage-examples) to `rwhois` yet.

**Comment by allmightyspiff** [comment]
@ATGE thanks for catching that, I've removed it from the docs.

**Pull request merged**
